<?php

/**
 * This is the model base class for the table "news_ids".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsIds".
 *
 * Columns in table "news_ids" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $news_id
 * @property integer $http_code
 * @property integer $created
 * @property integer $deleted
 *
 */
abstract class BaseNewsIds extends CActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news_ids';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewsIds|NewsIds', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('news_id, http_code, created', 'required'),
			array('news_id, http_code, created, deleted', 'numerical', 'integerOnly'=>true),
			array('deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, news_id, http_code, created, deleted', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'news_id' => Yii::t('app', 'News'),
			'http_code' => Yii::t('app', 'Http Code'),
			'created' => Yii::t('app', 'Created'),
			'deleted' => Yii::t('app', 'Deleted'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('news_id', $this->news_id);
		$criteria->compare('http_code', $this->http_code);
		$criteria->compare('created', $this->created);
		$criteria->compare('deleted', $this->deleted);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}